package top.putop.mi.db.model;

public class BBaseInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_base_info.id
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_base_info.pai_ming
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    private Integer paiMing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_base_info.b_name
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    private String bName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_base_info.shi_zhi
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    private Integer shiZhi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_base_info.is_hava_chi_cang
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    private String isHavaChiCang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_base_info.is_hb_have
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    private String isHbHave;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_base_info.coincode
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    private String coincode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_base_info.id
     *
     * @return the value of b_base_info.id
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_base_info.id
     *
     * @param id the value for b_base_info.id
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_base_info.pai_ming
     *
     * @return the value of b_base_info.pai_ming
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    public Integer getPaiMing() {
        return paiMing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_base_info.pai_ming
     *
     * @param paiMing the value for b_base_info.pai_ming
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    public void setPaiMing(Integer paiMing) {
        this.paiMing = paiMing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_base_info.b_name
     *
     * @return the value of b_base_info.b_name
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    public String getbName() {
        return bName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_base_info.b_name
     *
     * @param bName the value for b_base_info.b_name
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    public void setbName(String bName) {
        this.bName = bName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_base_info.shi_zhi
     *
     * @return the value of b_base_info.shi_zhi
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    public Integer getShiZhi() {
        return shiZhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_base_info.shi_zhi
     *
     * @param shiZhi the value for b_base_info.shi_zhi
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    public void setShiZhi(Integer shiZhi) {
        this.shiZhi = shiZhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_base_info.is_hava_chi_cang
     *
     * @return the value of b_base_info.is_hava_chi_cang
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    public String getIsHavaChiCang() {
        return isHavaChiCang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_base_info.is_hava_chi_cang
     *
     * @param isHavaChiCang the value for b_base_info.is_hava_chi_cang
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    public void setIsHavaChiCang(String isHavaChiCang) {
        this.isHavaChiCang = isHavaChiCang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_base_info.is_hb_have
     *
     * @return the value of b_base_info.is_hb_have
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    public String getIsHbHave() {
        return isHbHave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_base_info.is_hb_have
     *
     * @param isHbHave the value for b_base_info.is_hb_have
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    public void setIsHbHave(String isHbHave) {
        this.isHbHave = isHbHave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_base_info.coincode
     *
     * @return the value of b_base_info.coincode
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    public String getCoincode() {
        return coincode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_base_info.coincode
     *
     * @param coincode the value for b_base_info.coincode
     *
     * @mbg.generated Sat Sep 05 12:03:12 CST 2020
     */
    public void setCoincode(String coincode) {
        this.coincode = coincode;
    }


    @Override
    public String toString() {
        return "BBaseInfo{" +
                "id=" + id +
                ", paiMing=" + paiMing +
                ", bName='" + bName + '\'' +
                ", shiZhi=" + shiZhi +
                ", isHavaChiCang='" + isHavaChiCang + '\'' +
                ", isHbHave='" + isHbHave + '\'' +
                ", coincode='" + coincode + '\'' +
                '}';
    }
}