package top.putop.mi.db.model;

import java.util.Date;

public class BBuyPriceDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_buy_price_detail.id
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_buy_price_detail.fk_b_id
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    private Integer fkBId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_buy_price_detail.one_price
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    private Double onePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_buy_price_detail.create_time
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_buy_price_detail.end_time
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_buy_price_detail.id
     *
     * @return the value of b_buy_price_detail.id
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_buy_price_detail.id
     *
     * @param id the value for b_buy_price_detail.id
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_buy_price_detail.fk_b_id
     *
     * @return the value of b_buy_price_detail.fk_b_id
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public Integer getFkBId() {
        return fkBId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_buy_price_detail.fk_b_id
     *
     * @param fkBId the value for b_buy_price_detail.fk_b_id
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public void setFkBId(Integer fkBId) {
        this.fkBId = fkBId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_buy_price_detail.one_price
     *
     * @return the value of b_buy_price_detail.one_price
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public Double getOnePrice() {
        return onePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_buy_price_detail.one_price
     *
     * @param onePrice the value for b_buy_price_detail.one_price
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public void setOnePrice(Double onePrice) {
        this.onePrice = onePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_buy_price_detail.create_time
     *
     * @return the value of b_buy_price_detail.create_time
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_buy_price_detail.create_time
     *
     * @param createTime the value for b_buy_price_detail.create_time
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_buy_price_detail.end_time
     *
     * @return the value of b_buy_price_detail.end_time
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_buy_price_detail.end_time
     *
     * @param endTime the value for b_buy_price_detail.end_time
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}