package top.putop.mi.db.model;

import java.util.Date;

public class OdsBbPriceHis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_bb_price_his.id
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_bb_price_his.b_name
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    private String bName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_bb_price_his.year
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_bb_price_his.date
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_bb_price_his.start_price
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    private Double startPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_bb_price_his.max_price
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    private Double maxPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_bb_price_his.min_price
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    private Double minPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_bb_price_his.end_price
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    private Double endPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_bb_price_his.fk_b_id
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    private Integer fkBId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_bb_price_his.id
     *
     * @return the value of ods_bb_price_his.id
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_bb_price_his.id
     *
     * @param id the value for ods_bb_price_his.id
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_bb_price_his.b_name
     *
     * @return the value of ods_bb_price_his.b_name
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    public String getbName() {
        return bName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_bb_price_his.b_name
     *
     * @param bName the value for ods_bb_price_his.b_name
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    public void setbName(String bName) {
        this.bName = bName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_bb_price_his.year
     *
     * @return the value of ods_bb_price_his.year
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_bb_price_his.year
     *
     * @param year the value for ods_bb_price_his.year
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_bb_price_his.date
     *
     * @return the value of ods_bb_price_his.date
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_bb_price_his.date
     *
     * @param date the value for ods_bb_price_his.date
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_bb_price_his.start_price
     *
     * @return the value of ods_bb_price_his.start_price
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    public Double getStartPrice() {
        return startPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_bb_price_his.start_price
     *
     * @param startPrice the value for ods_bb_price_his.start_price
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    public void setStartPrice(Double startPrice) {
        this.startPrice = startPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_bb_price_his.max_price
     *
     * @return the value of ods_bb_price_his.max_price
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    public Double getMaxPrice() {
        return maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_bb_price_his.max_price
     *
     * @param maxPrice the value for ods_bb_price_his.max_price
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    public void setMaxPrice(Double maxPrice) {
        this.maxPrice = maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_bb_price_his.min_price
     *
     * @return the value of ods_bb_price_his.min_price
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    public Double getMinPrice() {
        return minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_bb_price_his.min_price
     *
     * @param minPrice the value for ods_bb_price_his.min_price
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    public void setMinPrice(Double minPrice) {
        this.minPrice = minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_bb_price_his.end_price
     *
     * @return the value of ods_bb_price_his.end_price
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    public Double getEndPrice() {
        return endPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_bb_price_his.end_price
     *
     * @param endPrice the value for ods_bb_price_his.end_price
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    public void setEndPrice(Double endPrice) {
        this.endPrice = endPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_bb_price_his.fk_b_id
     *
     * @return the value of ods_bb_price_his.fk_b_id
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    public Integer getFkBId() {
        return fkBId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_bb_price_his.fk_b_id
     *
     * @param fkBId the value for ods_bb_price_his.fk_b_id
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    public void setFkBId(Integer fkBId) {
        this.fkBId = fkBId;
    }


    @Override
    public String toString() {
        return "OdsBbPriceHis{" +
                "id='" + id + '\'' +
                ", bName='" + bName + '\'' +
                ", year='" + year + '\'' +
                ", date=" + date +
                ", startPrice=" + startPrice +
                ", maxPrice=" + maxPrice +
                ", minPrice=" + minPrice +
                ", endPrice=" + endPrice +
                ", fkBId=" + fkBId +
                '}';
    }
}