package top.putop.mi.db.model;

import java.util.Date;

public class OdsTbOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_tb_order.id
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_tb_order.exchange
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    private String exchange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_tb_order.account
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_tb_order.b_species
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    private String bSpecies;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_tb_order.order_no
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_tb_order.rule_type
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    private String ruleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_tb_order.transaction_type
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    private String transactionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_tb_order.b_nums
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    private Double bNums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_tb_order.single_price
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    private Double singlePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_tb_order.profit
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    private Double profit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_tb_order.profit_per
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    private Double profitPer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_tb_order.status
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_tb_order.remark
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_tb_order.last_ut
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    private Date lastUt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_tb_order.order_dt
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    private Date orderDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_tb_order.id
     *
     * @return the value of ods_tb_order.id
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_tb_order.id
     *
     * @param id the value for ods_tb_order.id
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_tb_order.exchange
     *
     * @return the value of ods_tb_order.exchange
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_tb_order.exchange
     *
     * @param exchange the value for ods_tb_order.exchange
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public void setExchange(String exchange) {
        this.exchange = exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_tb_order.account
     *
     * @return the value of ods_tb_order.account
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_tb_order.account
     *
     * @param account the value for ods_tb_order.account
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_tb_order.b_species
     *
     * @return the value of ods_tb_order.b_species
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public String getbSpecies() {
        return bSpecies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_tb_order.b_species
     *
     * @param bSpecies the value for ods_tb_order.b_species
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public void setbSpecies(String bSpecies) {
        this.bSpecies = bSpecies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_tb_order.order_no
     *
     * @return the value of ods_tb_order.order_no
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_tb_order.order_no
     *
     * @param orderNo the value for ods_tb_order.order_no
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_tb_order.rule_type
     *
     * @return the value of ods_tb_order.rule_type
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public String getRuleType() {
        return ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_tb_order.rule_type
     *
     * @param ruleType the value for ods_tb_order.rule_type
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public void setRuleType(String ruleType) {
        this.ruleType = ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_tb_order.transaction_type
     *
     * @return the value of ods_tb_order.transaction_type
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_tb_order.transaction_type
     *
     * @param transactionType the value for ods_tb_order.transaction_type
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_tb_order.b_nums
     *
     * @return the value of ods_tb_order.b_nums
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public Double getbNums() {
        return bNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_tb_order.b_nums
     *
     * @param bNums the value for ods_tb_order.b_nums
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public void setbNums(Double bNums) {
        this.bNums = bNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_tb_order.single_price
     *
     * @return the value of ods_tb_order.single_price
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public Double getSinglePrice() {
        return singlePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_tb_order.single_price
     *
     * @param singlePrice the value for ods_tb_order.single_price
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public void setSinglePrice(Double singlePrice) {
        this.singlePrice = singlePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_tb_order.profit
     *
     * @return the value of ods_tb_order.profit
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public Double getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_tb_order.profit
     *
     * @param profit the value for ods_tb_order.profit
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public void setProfit(Double profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_tb_order.profit_per
     *
     * @return the value of ods_tb_order.profit_per
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public Double getProfitPer() {
        return profitPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_tb_order.profit_per
     *
     * @param profitPer the value for ods_tb_order.profit_per
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public void setProfitPer(Double profitPer) {
        this.profitPer = profitPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_tb_order.status
     *
     * @return the value of ods_tb_order.status
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_tb_order.status
     *
     * @param status the value for ods_tb_order.status
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_tb_order.remark
     *
     * @return the value of ods_tb_order.remark
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_tb_order.remark
     *
     * @param remark the value for ods_tb_order.remark
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_tb_order.last_ut
     *
     * @return the value of ods_tb_order.last_ut
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public Date getLastUt() {
        return lastUt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_tb_order.last_ut
     *
     * @param lastUt the value for ods_tb_order.last_ut
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public void setLastUt(Date lastUt) {
        this.lastUt = lastUt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_tb_order.order_dt
     *
     * @return the value of ods_tb_order.order_dt
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public Date getOrderDt() {
        return orderDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_tb_order.order_dt
     *
     * @param orderDt the value for ods_tb_order.order_dt
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    public void setOrderDt(Date orderDt) {
        this.orderDt = orderDt;
    }
}