package top.putop.mi.db.dao;

import top.putop.mi.db.model.BBuyPriceDetail;

public interface BBuyPriceDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_buy_price_detail
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_buy_price_detail
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    int insert(BBuyPriceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_buy_price_detail
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    int insertSelective(BBuyPriceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_buy_price_detail
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    BBuyPriceDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_buy_price_detail
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    int updateByPrimaryKeySelective(BBuyPriceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_buy_price_detail
     *
     * @mbg.generated Fri Sep 04 12:19:43 CST 2020
     */
    int updateByPrimaryKey(BBuyPriceDetail record);
}