package top.putop.mi.db.dao;

import top.putop.mi.db.model.OdsBbPriceHis;

public interface OdsBbPriceHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_bb_price_his
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_bb_price_his
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    int insert(OdsBbPriceHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_bb_price_his
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    int insertSelective(OdsBbPriceHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_bb_price_his
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    OdsBbPriceHis selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_bb_price_his
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    int updateByPrimaryKeySelective(OdsBbPriceHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_bb_price_his
     *
     * @mbg.generated Sat Sep 05 10:31:06 CST 2020
     */
    int updateByPrimaryKey(OdsBbPriceHis record);
}